
stages:
  - eslint
  - typecheck
  - integration-test

eslint-backend:
  image: node:20
  stage: eslint
  tags:
    - shared-fi
  script:
    - cd backend
    - npm install
    - npm run lint

eslint-frontend:
  image: node:20
  stage: eslint
  tags:
    - shared-fi
  script:
    - cd frontend
    - npm install
    - npm run lint

typecheck-backend:
  image: node:20
  stage: typecheck
  tags:
    - shared-fi
  script:
    - cd backend
    - npm install
    - npm run typecheck

typecheck-frontend:
  image: node:20
  stage: typecheck
  tags:
    - shared-fi
  script:
    - cd frontend
    - npm install
    - npm run typecheck

integration-test:
  image: node:20
  services:
    - name: postgres:latest
      alias: postgres_db
      variables:
        POSTGRES_PASSWORD: prisma
        POSTGRES_DB: pb138
  variables:
    DATABASE_URL: "postgresql://postgres:prisma@postgres_db:5432/pb138?schema=public"
  stage: integration-test
  tags:
    - shared-fi

  script:
    - cd backend
    - npm install
    - npx prisma migrate dev
    - npx prisma db seed
    - echo "Waiting for services to be ready..."
    - sleep 2
    - npm run test
