services:
  db:
    image: postgres
    restart: always
    container_name: pb138-database
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: example
      POSTGRES_DB: pb138
