@startuml
skinparam shadowing false

title Database Diagram

entity User {
    * user_id : INT <<PK>>
    --
    * name : text
    * email : text <<UNIQUE>>
    * password : text
    profile_picture : image
}

entity Admin {
    * admin_id : INT <<PK>>
    --
    * email : text <<UNIQUE>>
    * name : text
    * password : text
}

entity Notebook {
    * notebook_id : INT <<PK>>
    --
    user_id : INT <<FK>>
    * title : text
    icon : text
    color : text
    tags : text

    * time_of_creation : DATETIME
    * last_time_of_edit : DATETIME
}

entity Note {
    * note_id : INT <<PK>>
    --
    notebook_id : INT <<FK>>
    * title : text
    * content : text
    tags : text

    * time_of_creation : DATETIME
    * last_time_of_edit : DATETIME
}

entity Calendar {
    * subject_id : INT <<PK>>
    --
    *user_id : INT <<FK>>
    * title : text
    color : text
}

entity Event {
    * event_id : INT <<PK>>
    --
    * subject_id : INT <<FK>>
    * title : text
    description : text
    tags : text
    color : text
}

entity Event_time {
    * event_time_id : INT <<PK>>
    --
    * event_id : INT <<FK>>
    * date : DATE
    * start_time : TIME
    duration : TIME
    repeats : ENUM('day', 'week', 'month', 'year')
}

entity FlashDeck {
    * flashcard_id : INT <<PK>>
    --
    * subject_id : INT <<FK>>
    * title : text
    description : text
    color : text
    icon: image
    tags: text

    * time_of_creation : DATETIME
    * last_time_of_edit : DATETIME
}

entity FlashCard {
    * flashcard_id : INT <<PK>>
    --
    * deck_id : INT <<FK>>
    * question : text

    * time_of_creation : DATETIME
    * last_time_of_edit : DATETIME
}

entity FlashCardAnswer {
    * answer_id : INT <<PK>>
    --
    * flashcard_id : INT <<FK>>
    * answer : text
    * is_correct : BOOLEAN
}

Admin       ||--o{ User             : manages
User        ||--o{ Notebook         : creates
Notebook    ||--o{ Note             : contains
User        ||--|| Calendar         : has
Calendar    ||--o{ Event            : contains
Event       ||--o{ Event_time       : has
User        ||--o{ FlashDeck        : creates
FlashDeck   ||--o{ FlashCard        : contains
FlashCard   ||--o{ FlashCardAnswer  : has
Notebook    ||--o{ FlashDeck        : links into

@enduml
