services:
  postgres_db:
    image: postgres
    restart: always
    container_name: pb138-database
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: prisma
      POSTGRES_DB: pb138
    networks:
      - prisma-network
    volumes:
      - postgres_data:/var/lib/postgresql/data

  prisma-studio:
    image: node:lts-alpine3.17
    command: npx prisma studio --port 5555 --browser none
    ports:
      - "5555:5555"
    networks:
      - prisma-network

networks:
  prisma-network:

volumes:
  postgres_data:

