services:
  postgres_db:
    image: postgres
    restart: always
    container_name: pb138-database
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: prisma
      POSTGRES_DB: pb138
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
